services:
  chatbot-api:
    build: .
    container_name: chatbot-immobilier-api
    ports:
      - "8000:8000"
    environment:
      - API_KEY=${API_KEY}
      - BASE_URL=${BASE_URL}
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    volumes:
      - ./ics_out:/app/ics_out
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - chatbot-network

  # Service optionnel pour les logs
  nginx:
    image: nginx:alpine
    container_name: chatbot-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - chatbot-api
    restart: unless-stopped
    networks:
      - chatbot-network
    profiles:
      - production

networks:
  chatbot-network:
    driver: bridge

volumes:
  chatbot-data:
